services:
  - type: web
    name: control-system-backend
    runtime: go
    env: go
    buildCommand: |
      # Установка Python и системных зависимостей
      sudo apt-get update
      sudo apt-get install -y python3.9 python3-pip python3.9-dev
      sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
      
      # Установка Python-библиотек
      python3 -m pip install --upgrade pip
      python3 -m pip install -r compute/requirements.txt
      
      # Сборка Go-приложения
      go build -o app ./backend
    startCommand: ./app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MPLCONFIGDIR
        value: "/tmp/.matplotlib"
